### ISSUE TITLE
Алгоритм обработки действий игрока

### ISSUE THREAD

**Issue by Linaya** [ri57-sibsutis/hangman#5]
Алгоритм должен обрабатывать следующие действия:
1. Нажатие буквы на клавиатуре, которая содержится в угадываемом слове.
2. Нажатие буквы на клавиатуре, которая не содержится в угадываемом слове.

В первом случае алгоритм должен выполнить поиск нажатой буквы на клавиатуре в угадываемом слове, предложить отобразить все найденные в слове буквы и убрать букву из предлагаемого алфавита для угадывания слова.
Во втором случае алгоритм должен так же выполнить поиск нажатой буквы в слове, но затем просто убрать букву из предлагаемого алфавита для угадывания слова и увеличить количество ошибок на единицу.

При угадывании слова или достижении предельного количества ошибок, алгоритм должен возвращать код статуса игры.
Для достижения качества работы алгоритма требуется сделать ввод только английских букв и сделать соответствующий возврат кода ошибки при вводе неверного символа.

**Comment by evgeny-p** [comment]
Задача сформулирована так, что кажется дублирующей #7. Насколько я понимаю, здесь подразумевается реализация игровой модели.
