### ISSUE TITLE
Создание игрового интерфейса

### ISSUE THREAD

**Issue by Linaya** [ri57-sibsutis/hangman#6]
Необходимо создать игровой интерфейс, который позволит определить количество угадываемых символов в слове на основе случайно выбранного слова из базы слов, текущий статус прорисовки виселицы, текущий статус алфавита угадываемых букв в слове и игровые достижения.

Для разработки интерфейса будет использоваться графический туллкит под названием GTK+ с применением инструментария создания интерфейсов Glade.

**Comment by evgeny-p** [comment]
> ресурс, с помощью которого будет сделана связь панелей и данных программы выберем чуть позже
1. Что Вы называете «ресурсом»?
2. Если подразумевалась библиотека для разработки графического интерфейса, и ее выбор требует времени и сил, то нужно завести отдельную задачу вида:

> **Выбор библиотеки для реализации GUI**
> В рамках задачи нужно рассмотреть существующие решения для разработки графического интерфейса и выбрать одно из них для использования в проекте. Написать статью, в которой зафиксировать критерии выбора и принятое решение.
