### ISSUE TITLE
Создание визуализаций интерфейса, вызываемых событиями игрового алгоритма

### ISSUE THREAD

**Issue by Linaya** [ri57-sibsutis/hangman#7]
Необходимо применить созданный интерфейс к игровым алгоритмам.

Интерфейс должен, используя алгоритм обработки действий игрока, выполнять следующие действия:
1. Если игрок выбрал букву, которой нет в угадываемом слове, то эта буква должна загореться красным в отображаемом алфавите угадываемых букв, или вовсе исчезнуть.
2. Если игрок выбрал букву, которая есть в угадываемом слове, то эта буква должна загореться зелёным или так же вовсе исчезнуть с экрана, а также эта буква должна появиться в тех клетках угадываемого слова, в которых она находится.
3. Если игрок проиграл (не угадал 3 буквы в слове), то интерфейс должен сообщить о проигрыше и предложить реванш.
4. Если игрок угадал слово и выиграл, то интерфейс должен сообщить о победе и предложить сыграть ещё раз.
5. При достижении 5 побед, в правом углу экрана должна появиться медалька "Cats Savior" как достижение за спасение кошек из виселицы. Медальки отображаются только в рамках одной игровой сессии.
6. При достижении 5 проигрышей, в правом углу экрана должна появиться медалька "Cats Killer" как достижение за умышленное убийство кошек виселицей. Медальки отображаются только в рамках одной игровой сессии.
7. Если игрок вводит неверный символ или букву алфавита, отличного от английского, интерфейс должен выдать соответствующее предупреждение.

**Comment by evgeny-p** [comment]
Заголовок задачи непонятен. Формулировка вида «Визуализация игровых событий» соответствует тому, что подразумевалось?

**Comment by DX37** [comment]
Задача объединена с задачей #6.

**Comment by Linaya** [comment]
Упс, поторопились. Задача возвращена.
